👍 Able to specify where to run tests.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -13,7 +13,7 @@ inputs:
   where-to-run-test:
     description: "Where to run the test. If none is specified, run from the root directory."
     required: false
-    default: ""
+    default: "./"
   python-version:
     description: "Python version to use. Default is 3.11."
     required: false
@@ -25,6 +25,13 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Validate input parameters is not empty
+      run: |
+        [[ "${{ inputs.lock-file-path }}" ]] || { echo "Error lock-file-path input is empty" ; exit 1; }
+        [[ "${{ inputs.src-directory }}" ]] || { echo "Error src-directory input is empty" ; exit 1; }
+        [[ "${{ inputs.test-directory }}" ]] || { echo "Error test-directory input is empty" ; exit 1; }
+      shell: bash
+
     - name: Tree before checkout
       run: tree -a
       shell: bash
@@ -41,7 +48,7 @@ runs:
       uses: actions/checkout@v4
       with:
         repository: Century-ss/python-mutation-report
-        path: Century-ss/python-mutesting-report
+        path: "${{ inputs.where-to-run-test }}/Century-ss/python-mutesting-report"
         sparse-checkout: |
           scripts
           temporary
@@ -52,34 +59,29 @@ runs:
       run: tree -a
       shell: bash
 
-    - name: Validate input parameters is not empty
-      run: |
-        [[ "${{ inputs.lock-file-path }}" ]] || { echo "Error lock-file-path input is empty" ; exit 1; }
-        [[ "${{ inputs.src-directory }}" ]] || { echo "Error src-directory input is empty" ; exit 1; }
-        [[ "${{ inputs.test-directory }}" ]] || { echo "Error test-directory input is empty" ; exit 1; }
-      shell: bash
-
     - name: Get change file list
       env:
         GITHUB_TOKEN: ${{ github.token }}
         URL: ${{ github.event.pull_request.html_url }}
       run: |
-        cd Century-ss/python-mutesting-report
+        cd "${{ inputs.where-to-run-test }}/Century-ss/python-mutesting-report"
         gh pr diff "${URL}" --name-only > temporary/PR_diff_files.txt
       # Strings with \n cannot be set in $GITHUB_OUTPUT or $GITHUB_ENV, so use a text file instead.
       shell: bash
 
     - name: Debug
       run: |
-        cd Century-ss/python-mutesting-report
+        cd "${{ inputs.where-to-run-test }}/Century-ss/python-mutesting-report"
         cat temporary/PR_diff_files.txt
       shell: bash
 
     - name: Make mutmut run command from PR changed files
-      run: python3 Century-ss/python-mutesting-report/scripts/make_command_of_run.py
+      # It needs to be run from the root of the repository as it retrieves the files under src and test with glob.
+      run: python3 "${{ inputs.where-to-run-test }}/Century-ss/python-mutesting-report/scripts/make_command_of_run.py
       env:
         SRC_DIRECTORY: ${{ inputs.src-directory }}
         TEST_DIRECTORY: ${{ inputs.test-directory }}
+        WHERE_TO_RUN_TEST: ${{ inputs.where-to-run-test }}
       shell: bash
 
     - name: Set up Python
@@ -88,7 +90,8 @@ runs:
         python-version: "${{ inputs.python-version }}"
 
     - name: Generate requirements.txt
-      run: python3 Century-ss/python-mutesting-report/scripts/generate_requirements_from_pipfile.py
+      # Uses the path of the lock file from root, so must be run from root.
+      run: python3 "${{ inputs.where-to-run-test }}/Century-ss/python-mutesting-report/scripts/generate_requirements_from_pipfile.py"
       env:
         LOCK_FILE_PATH: ${{ inputs.lock-file-path }}
       shell: bash
@@ -108,20 +111,28 @@ runs:
 
     - name: Create __init__.py in test directory
       run: |
-        cd ${{ inputs.test-directory }}
-        find . -name '__pycache__' -prune -o -type d -exec touch {}/__init__.py \;
-      shell: bash
+        cd "${{ inputs.test-directory }}"
+        find . \( -name '__pycache__' -o -name 'Century-ss' \) -prune -o -type d -exec touch {}/__init__.py \;
+      shell:
+        bash
+        # find . -name '__pycache__' -prune -o -type d -exec touch {}/__init__.py \;
 
     - name: cat mutmut-run.sh
-      run: cat Century-ss/python-mutesting-report/temporary/mutmut-run.sh
+      run: cat "${{ inputs.where-to-run-test }}/Century-ss/python-mutesting-report/temporary/mutmut-run.sh"
       shell: bash
 
     - name: Execute mutation test
-      run: bash Century-ss/python-mutesting-report/temporary/mutmut-run.sh
+      run: |
+        cd "${{ inputs.where-to-run-test }}"
+        bash "Century-ss/python-mutesting-report/temporary/mutmut-run.sh"
       shell: bash
       continue-on-error: true
       # If all mutants cannot be killed, an error occurs with an exit code of 2.
       # Even if an error occurs, continue-on-error is required to allow subsequent steps to be performed
+
+    - name: Debug run.txt
+      run: cat "${{ inputs.where-to-run-test }}/Century-ss/python-mutesting-report/temporary/run.txt"
+      shell: bash
 
     - name: Debug tree
       run: tree -a
@@ -129,26 +140,23 @@ runs:
 
     - name: Output mutation test result to a text file.
       run: |
+        cd "${{ inputs.where-to-run-test }}"
         mutmut html
         mutmut junitxml --suspicious-policy=error > Century-ss/python-mutesting-report/temporary/junit.xml
       shell: bash
 
     - name: Reshape result for PR comment
-      run: python3 Century-ss/python-mutesting-report/scripts/reshape_result_for_PR_comment.py
+      run: |
+        cd "${{ inputs.where-to-run-test }}"
+        python3 Century-ss/python-mutesting-report/scripts/reshape_result_for_PR_comment.py"
       shell: bash
-
-    # - name: Show github context and environment variable
-    #   run: |
-    #     echo '${{ toJSON(github) }}'
-    #     printenv
-    #   shell: bash
 
     - name: Post comments to PR
       # if: ${{ success() && github.event_name == 'pull_request' }}
       env:
         GITHUB_TOKEN: ${{ github.token }}
         URL: ${{ github.event.pull_request.html_url }}
-      run: gh pr comment -F PR_comment.txt "${URL}"
+      run: gh pr comment -F "${{ inputs.where-to-run-test }}/PR_comment.txt" "${URL}"
       shell: bash
 
     # - name: Upload artifact text file?
@@ -157,3 +165,9 @@ runs:
     #     GITHUB_TOKEN: ${{ github.token }}
     #     URL: ${{ github.event.pull_request.html_url }}
     #   run: gh pr comment -F result.txt "${URL}"
+
+    # - name: Show github context and environment variable
+    #   run: |
+    #     echo '${{ toJSON(github) }}'
+    #     printenv
+    #   shell: bash
